-- Seed de Watchlist para WTD (actualizado)
-- Borra los datos previos y carga la lista completa

DELETE FROM watchlist_items;

INSERT INTO watchlist_items (title, type, status, release_date, created_at) VALUES
('Daredevil: Born Again', 'SERIES', 'NO', NULL, NOW()),
('Adolescence', 'SERIES', 'SOON', NULL, NOW()),
('The Studio', 'SERIES', 'YES', NULL, NOW()),
('Snowpiercer (S4)', 'SERIES', 'NO', NULL, NOW()),
('How To Sell Drugs Online (S4)', 'SERIES', 'NO', NULL, NOW()),
('Black Mirror (S7)', 'SERIES', 'NO', NULL, NOW()),
('Hacks (S4)', 'SERIES', 'NO', NULL, NOW()),
('The Last of Us (S2)', 'SERIES', 'YES', NULL, NOW()),
('You (S5)', 'SERIES', 'NO', NULL, NOW()),
('El Eternauta', 'SERIES', 'SOON', NULL, NOW()),
('Chespirito', 'SERIES', 'NO', NULL, NOW()),
('Ginny & Georgia (S3)', 'SERIES', 'YES', NULL, NOW()),
('Ironheart', 'SERIES', 'SOON', NULL, NOW()),
('The Bear (S4)', 'SERIES', 'NO', NULL, NOW()),
('Squid Games (S3)', 'SERIES', 'NO', NULL, NOW()),
('Sandman (S2)', 'SERIES', 'NO', NULL, NOW()),
('Menem', 'SERIES', 'NO', NULL, NOW()),
('The Summer I Turned Pretty (S3)', 'SERIES', 'YES', NULL, NOW()),
('Poker Face (S2)', 'SERIES', 'NO', NULL, NOW()),
('Wednesday (S2)', 'SERIES', 'YES', NULL, NOW()),
('Peacemaker (S2)', 'SERIES', 'SOON', NULL, NOW()),
('Eyes of Wakanda', 'SERIES', 'NO', NULL, NOW()),
('Only Murders in the Building (S5)', 'SERIES', 'NO', NULL, NOW()),
('Gen V (S2)', 'SERIES', 'YES', NULL, NOW()),
('The Morning Show (S4)', 'SERIES', 'NO', NULL, NOW()),
('Slow Horses (S5)', 'SERIES', 'NO', NULL, NOW()),
('Marvel Zombies', 'SERIES', 'NO', NULL, NOW()),
('The Diplomat (S3)', 'SERIES', 'SOON', NULL, NOW()),
('It: Welcome to Derry', 'SERIES', 'SOON', NULL, NOW()),
('The Witcher (S4)', 'SERIES', 'NO', NULL, NOW()),
('Mayor of Kingstown (S4)', 'SERIES', 'NO', NULL, NOW()),
('Maxton Hall (S2)', 'SERIES', 'YES', NULL, NOW()),
('Stranger Things (S5)', 'SERIES', 'YES', NULL, NOW()),
('Percy Jackson (S2)', 'SERIES', 'SOON', NULL, NOW()),
('Fallout (S2)', 'SERIES', 'NO', NULL, NOW()),
('Emily in Paris (S5)', 'SERIES', 'NO', NULL, NOW()),
('Beast Games (S2)', 'SERIES', 'YES', NULL, NOW()),
('The Pitt (S2)', 'SERIES', 'NO', NULL, NOW()),
('The Night Manager (S2)', 'SERIES', 'NO', NULL, NOW()),
('Wonder Man (S1)', 'SERIES', 'NO', NULL, NOW()),
('The Night Agent (S3)', 'SERIES', 'SOON', NULL, NOW()),
('Young Sherlock', 'SERIES', 'SOON', DATE '2026-03-04', NOW()),
('The Boys (S5)', 'SERIES', 'YES', DATE '2026-04-08', NOW()),
('Euphoria (S3)', 'SERIES', 'SOON', DATE '2026-04-13', NOW()),
('Beef (S2)', 'SERIES', 'SOON', DATE '2026-04-16', NOW()),
('El Encargado (S4)', 'SERIES', 'SOON', DATE '2026-05-01', NOW()),
('Off Campus', 'SERIES', 'YES', DATE '2026-05-13', NOW()),
('Spider Noir', 'SERIES', 'SOON', DATE '2026-05-27', NOW()),
('Cape Fear (S1)', 'SERIES', 'SOON', DATE '2026-06-05', NOW()),
('Every Year After', 'SERIES', 'SOON', DATE '2026-06-10', NOW()),
('Sugar (S2)', 'SERIES', 'SOON', DATE '2026-06-19', NOW()),
('The Bear (S5)', 'SERIES', 'SOON', DATE '2026-06-26', NOW()),
('Elle (S1)', 'SERIES', 'SOON', DATE '2026-07-01', NOW()),
('Little House on the Prairie', 'SERIES', 'SOON', DATE '2026-07-09', NOW()),
('Ride or Die', 'SERIES', 'SOON', DATE '2026-07-15', NOW()),
('Lucky', 'SERIES', 'SOON', DATE '2026-07-15', NOW()),
('El Mapa de los Anhelos', 'SERIES', 'SOON', DATE '2026-07-17', NOW()),
('Moria', 'SERIES', 'SOON', DATE '2026-08-14', NOW()),
('Lanterns', 'SERIES', 'SOON', DATE '2026-08-17', NOW()),
('The Love Hypothesis', 'SERIES', 'SOON', DATE '2026-09-23', NOW()),
('Sonic 3', 'MOVIE', 'NO', NULL, NOW()),
('Anora', 'MOVIE', 'YES', NULL, NOW()),
('A Complete Unknown', 'MOVIE', 'YES', NULL, NOW()),
('Conclave', 'MOVIE', 'YES', NULL, NOW()),
('Companion', 'MOVIE', 'YES', NULL, NOW()),
('The Brutalist', 'MOVIE', 'YES', NULL, NOW()),
('Captain America: Brave New World', 'MOVIE', 'YES', NULL, NOW()),
('Mickey 17', 'MOVIE', 'YES', NULL, NOW()),
('A Minecraft Movie', 'MOVIE', 'NO', NULL, NOW()),
('Warfare', 'MOVIE', 'NO', NULL, NOW()),
('Sinners', 'MOVIE', 'SOON', NULL, NOW()),
('Thunderbolts*', 'MOVIE', 'YES', NULL, NOW()),
('Final Destination: Bloodlines', 'MOVIE', 'SOON', NULL, NOW()),
('Mission Impossible 8', 'MOVIE', 'SOON', NULL, NOW()),
('Lilo & Stitch', 'MOVIE', 'YES', NULL, NOW()),
('Ballerina', 'MOVIE', 'NO', NULL, NOW()),
('Elio', 'MOVIE', 'NO', NULL, NOW()),
('How To Train Your Dragon', 'MOVIE', 'YES', NULL, NOW()),
('F1', 'MOVIE', 'YES', NULL, NOW()),
('M3GAN 2.0', 'MOVIE', 'YES', NULL, NOW()),
('Jurassic World Rebirth', 'MOVIE', 'SOON', NULL, NOW()),
('Superman', 'MOVIE', 'YES', NULL, NOW()),
('The Fantastic Four: First Steps', 'MOVIE', 'YES', NULL, NOW()),
('Amores Materialistas', 'MOVIE', 'YES', NULL, NOW()),
('La Hora de la Desaparición', 'MOVIE', 'YES', NULL, NOW()),
('Homo Argentum', 'MOVIE', 'YES', NULL, NOW()),
('The Conjuring: Last Rites', 'MOVIE', 'SOON', NULL, NOW()),
('One Battle After Another', 'MOVIE', 'YES', NULL, NOW()),
('Avatar: The Way Of Water (Re)', 'MOVIE', 'YES', NULL, NOW()),
('The Black Phone 2', 'MOVIE', 'YES', NULL, NOW()),
('Now You See Me 3', 'MOVIE', 'YES', NULL, NOW()),
('Harry Potter: Goblet of Fire (Re)', 'MOVIE', 'YES', NULL, NOW()),
('Wicked: For Good', 'MOVIE', 'SOON', NULL, NOW()),
('Zootopia 2', 'MOVIE', 'YES', NULL, NOW()),
('Five Nights At Freddy''s 2', 'MOVIE', 'NO', NULL, NOW()),
('Avatar: Fire And Ash', 'MOVIE', 'YES', NULL, NOW()),
('The Housemaid', 'MOVIE', 'SOON', NULL, NOW()),
('Marty Supreme', 'MOVIE', 'SOON', NULL, NOW()),
('Mercy', 'MOVIE', 'SOON', NULL, NOW()),
('Scream 7', 'MOVIE', 'SOON', NULL, NOW()),
('Hoppers', 'MOVIE', 'YES', NULL, NOW()),
('Project Hail Mary', 'MOVIE', 'YES', NULL, NOW()),
('The Super Mario Galaxy Movie', 'MOVIE', 'SOON', NULL, NOW()),
('The Drama', 'MOVIE', 'YES', NULL, NOW()),
('Michael', 'MOVIE', 'SOON', NULL, NOW()),
('The Devil Wears Prada 2', 'MOVIE', 'YES', NULL, NOW()),
('Mandalorian And Grogu', 'MOVIE', 'SOON', DATE '2026-05-21', NOW()),
('Toy Story 5', 'MOVIE', 'SOON', DATE '2026-06-17', NOW()),
('Supergirl', 'MOVIE', 'YES', DATE '2026-06-24', NOW()),
('Minions & Monsters', 'MOVIE', 'SOON', DATE '2026-06-25', NOW()),
('Moana', 'MOVIE', 'SOON', DATE '2026-07-09', NOW()),
('The Odyssey', 'MOVIE', 'SOON', DATE '2026-07-16', NOW()),
('Spider-Man: Brand New Day', 'MOVIE', 'SOON', DATE '2026-07-30', NOW()),
('The Invite', 'MOVIE', 'SOON', DATE '2026-08-06', NOW()),
('The End of Oak Street', 'MOVIE', 'SOON', DATE '2026-08-13', NOW());
